---
title: "R Notebook"
output: html_notebook
---

# Install/Load Required Packages

```{r setup, message=FALSE, warning=FALSE}
packages <- c("arules", "arulesViz", "tidyverse", "haven", "fastDummies")

# Installing Packages
# install.packages(packages, update = TRUE, ask = FALSE) 
  
# Loading Packages
for(package in packages) {
  do.call("library", list(package))
}
```

# Data Processing

```{r data_processing}
# Load data from NHANES into prescriptions_df
prescriptions_df <- read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/RXQ_RX_J.XPT")

# Filter to prescriptions that were taken in the last month
# Select patients (SEQN) and drug name (RXXDRUG) 
prescriptions_df <- prescriptions_df %>%
  filter(RXDUSE == 1) %>% 
  select(SEQN, RXDDRUG)

# View dataframe
prescriptions_df
```

```{r one_hot}
prescriptions_df <- prescriptions_df %>% 
  filter(
    RXDDRUG != "55555",
    RXDDRUG != "77777",
    RXDDRUG != "99999",
    RXDDRUG != ""
  ) %>%
  group_by(SEQN) %>% 
  summarize(RXDDRUG = list(unique(RXDDRUG)))

prescriptions_df
```

# Mine Frequent Itemsets

```{r frequent_itemsets}
frequent_itemsets <- apriori(
  as(prescriptions_df$RXDDRUG, "transactions"), 
  parameter = list(supp=0.005, target="frequent itemsets")
)

frequent_itemsets <- inspect(frequent_itemsets) %>% 
  arrange(desc(support))

frequent_itemsets
```

```{r association_rules}
rules <- apriori(
  as(prescriptions_df$RXDDRUG, "transactions"), 
  parameter = list(supp=0.005, conf=0.005, target="rules")
)

rules <-data.frame(inspect(rules)) %>%
  filter(
    lift >= 1,
    lhs != "{}",
    rhs != "{}"
  ) %>%
  select(-Var.2) %>%
  arrange(desc(lift))

rules
```
